SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `smartmart` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `smartmart` ;

CREATE TABLE IF NOT EXISTS `smartmart`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
   `us_user_name` VARCHAR(15) NULL,
   `us_password` VARCHAR(200) NULL,
	`us_user_type` VARCHAR(1) NULL,
	`us_email` VARCHAR(1) NULL,
	`us_mobile_number` BIGINT(10) NULL,
	`us_confirmed` BOOLEAN NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;